os: linux
dist: xenial # Ubuntu 16.04
language: bash
arch: amd64 # Architecture signifying a containerized version of Linux to boot faster
# Only build pushes to master branch
branches:
  only:
    - master
    - nathan
    - dev
    - test
    - foo

# Export variables
env:
  - tf_version=0.12.25 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

# Install dependencies
before_install:
  - sudo apt-get install -y -qq unzip
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

# Terraform Plan and Apply
# Plan only on pull requests, Apply on merged code
jobs:
  include:
    - stage: terraform plan
      # Only run terraform validate and plan state if within a pull request
      if: type IN (push) and branch = test
      script:
        - git branch
        - git branch -a
        - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        - git fetch --all
        - git branch -a
        - ./merge.sh $USER_NAME $PASS_WORD
        -
    - stage: terraform apply
      # Only run terraform apply stage if outside of a pull request
      if: type IN (push) and branch = dev
      script:
        - echo "hey!"
        - terraform init $tf_init_cli_options
        - terraform apply $tf_apply_cli_options
        - terraform destroy -auto-approve
        - echo "No error, infra destroyed completely"
